# This file may be used to create an environment using:
# $ conda create --name <env> --file <this file>
# platform: win-64
@EXPLICIT
https://repo.anaconda.com/pkgs/main/win-64/blas-1.0-mkl.conda
https://repo.anaconda.com/pkgs/main/win-64/ca-certificates-2023.08.22-haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/icc_rt-2022.1.0-h6049295_2.conda
https://conda.anaconda.org/conda-forge/win-64/libexpat-2.5.0-h63175ca_1.conda
https://conda.anaconda.org/conda-forge/noarch/poppler-data-0.4.12-hd8ed1ab_0.conda
https://repo.anaconda.com/pkgs/main/noarch/tzdata-2023c-h04d1e81_0.conda
https://repo.anaconda.com/pkgs/main/win-64/vs2015_runtime-14.27.29016-h5e58377_2.conda
https://conda.anaconda.org/conda-forge/win-64/expat-2.5.0-h63175ca_1.conda
https://repo.anaconda.com/pkgs/main/win-64/vc-14.2-h21ff451_1.conda
https://repo.anaconda.com/pkgs/main/win-64/bzip2-1.0.8-he774522_0.conda
https://repo.anaconda.com/pkgs/main/win-64/cfitsio-3.470-h2bbff1b_7.conda
https://repo.anaconda.com/pkgs/main/win-64/geos-3.8.0-h33f27b4_0.conda
https://repo.anaconda.com/pkgs/main/win-64/giflib-5.2.1-h8cc25b3_3.conda
https://repo.anaconda.com/pkgs/main/win-64/icu-58.2-ha925a31_3.conda
https://repo.anaconda.com/pkgs/main/win-64/intel-openmp-2023.1.0-h59b6b97_46319.conda
https://repo.anaconda.com/pkgs/main/win-64/jpeg-9e-h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/lerc-3.0-hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libbrotlicommon-1.0.9-h2bbff1b_7.conda
https://repo.anaconda.com/pkgs/main/win-64/libdeflate-1.17-h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/libffi-3.4.4-hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libiconv-1.16-h2bbff1b_2.conda
https://repo.anaconda.com/pkgs/main/win-64/libwebp-base-1.3.2-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/lz4-c-1.9.4-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/openssl-3.0.11-h2bbff1b_2.conda
https://repo.anaconda.com/pkgs/main/win-64/pcre-8.45-hd77b12b_0.conda
https://conda.anaconda.org/conda-forge/win-64/pixman-0.38.0-hfa6e2cd_1003.tar.bz2
https://conda.anaconda.org/conda-forge/win-64/qhull-2020.2-h70d2c02_2.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/sqlite-3.41.2-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tbb-2021.8.0-h59b6b97_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tk-8.6.12-h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/xerces-c-3.2.4-hd77b12b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/xz-5.4.2-h8cc25b3_0.conda
https://repo.anaconda.com/pkgs/main/win-64/zlib-1.2.13-h8cc25b3_0.conda
https://conda.anaconda.org/conda-forge/win-64/freexl-1.0.6-ha8e266a_0.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/glib-2.69.1-h5dc1a3c_2.conda
https://repo.anaconda.com/pkgs/main/win-64/hdf4-4.2.13-h712560f_2.conda
https://repo.anaconda.com/pkgs/main/win-64/hdf5-1.12.1-h51c971a_3.conda
https://repo.anaconda.com/pkgs/main/win-64/krb5-1.20.1-h5b6d351_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libbrotlidec-1.0.9-h2bbff1b_7.conda
https://repo.anaconda.com/pkgs/main/win-64/libbrotlienc-1.0.9-h2bbff1b_7.conda
https://repo.anaconda.com/pkgs/main/win-64/libclang13-14.0.6-default_h8e68704_1.conda
https://repo.anaconda.com/pkgs/main/win-64/libpng-1.6.39-h8cc25b3_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libssh2-1.10.0-he2ea4bf_2.conda
https://repo.anaconda.com/pkgs/main/win-64/libxml2-2.10.4-h0ad7f3c_1.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl-2023.1.0-h6b88ed4_46357.conda
https://repo.anaconda.com/pkgs/main/win-64/pcre2-10.42-h0ff8eda_0.conda
https://repo.anaconda.com/pkgs/main/win-64/proj-6.2.1-h3758d61_0.conda
https://repo.anaconda.com/pkgs/main/win-64/python-3.11.5-he1021f5_0.conda
https://repo.anaconda.com/pkgs/main/win-64/zstd-1.5.5-hd43e919_0.conda
https://repo.anaconda.com/pkgs/main/win-64/blosc-1.21.3-h6c2663c_0.conda
https://conda.anaconda.org/conda-forge/win-64/boost-cpp-1.74.0-h5b4e17d_6.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/brotli-bin-1.0.9-h2bbff1b_7.conda
https://conda.anaconda.org/conda-forge/win-64/cairo-1.16.0-h63a05c6_1001.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/colorama-0.4.6-py311haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/cycler-0.11.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/freetype-2.12.1-ha860e81_0.conda
https://repo.anaconda.com/pkgs/main/win-64/joblib-1.2.0-py311haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/kealib-1.5.0-hde4a422_1.conda
https://repo.anaconda.com/pkgs/main/win-64/kiwisolver-1.4.4-py311hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libclang-14.0.6-default_hb5a9fac_1.conda
https://repo.anaconda.com/pkgs/main/win-64/libcurl-8.1.1-h86230a5_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libpq-12.15-h906ac69_1.conda
https://repo.anaconda.com/pkgs/main/win-64/libspatialite-4.3.0a-h6ec8781_23.conda
https://repo.anaconda.com/pkgs/main/win-64/libtiff-4.5.1-hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/libxslt-1.1.37-h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/libzip-1.8.0-h289538f_1.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl-service-2.4.0-py311h2bbff1b_1.conda
https://repo.anaconda.com/pkgs/main/noarch/munkres-1.1.4-py_0.conda
https://repo.anaconda.com/pkgs/main/win-64/packaging-23.1-py311haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/ply-3.11-py311haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pyparsing-3.0.9-py311haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-tzdata-2023.3-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pytz-2023.3.post1-py311haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/setuptools-68.0.0-py311haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/six-1.16.0-pyhd3eb1b0_1.conda
https://repo.anaconda.com/pkgs/main/noarch/threadpoolctl-2.2.0-pyh0d69192_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tiledb-2.3.3-hd8964de_3.conda
https://repo.anaconda.com/pkgs/main/noarch/toml-0.10.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tornado-6.3.2-py311h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/wheel-0.41.2-py311haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/brotli-1.0.9-h2bbff1b_7.conda
https://repo.anaconda.com/pkgs/main/win-64/fontconfig-2.14.1-h9c4af85_2.conda
https://repo.anaconda.com/pkgs/main/win-64/geotiff-1.7.0-h4545760_1.conda
https://repo.anaconda.com/pkgs/main/win-64/lcms2-2.12-h83e58a3_0.conda
https://conda.anaconda.org/conda-forge/win-64/libkml-1.3.0-h9859afa_1014.tar.bz2
https://repo.anaconda.com/pkgs/main/win-64/libnetcdf-4.8.1-h6685c40_4.conda
https://repo.anaconda.com/pkgs/main/win-64/libwebp-1.3.2-hbc33d0d_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-base-1.26.0-py311hd01c5d8_0.conda
https://repo.anaconda.com/pkgs/main/win-64/openjpeg-2.4.0-h4fc8c34_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pip-23.2.1-py311haa95532_0.conda
https://repo.anaconda.com/pkgs/main/noarch/python-dateutil-2.8.2-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/qt-main-5.15.2-h879a1e9_9.conda
https://repo.anaconda.com/pkgs/main/win-64/sip-6.6.2-py311hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/tqdm-4.65.0-py311h746a85d_0.conda
https://repo.anaconda.com/pkgs/main/noarch/fonttools-4.25.0-pyhd3eb1b0_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pillow-9.4.0-py311hd77b12b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/poppler-22.12.0-h268424c_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pyqt5-sip-12.11.0-py311hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/qt-webengine-5.15.9-h5bd16bc_7.conda
https://repo.anaconda.com/pkgs/main/win-64/libgdal-3.6.2-h676b171_3.conda
https://repo.anaconda.com/pkgs/main/win-64/qtwebkit-5.212-h2bbfb41_5.conda
https://repo.anaconda.com/pkgs/main/win-64/pyqt-5.15.7-py311hd77b12b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/bottleneck-1.3.5-py311h5bb9823_0.conda
https://repo.anaconda.com/pkgs/main/win-64/contourpy-1.0.5-py311h59b6b97_0.conda
https://repo.anaconda.com/pkgs/main/win-64/gdal-3.6.2-py311h4e7b5b2_3.conda
https://repo.anaconda.com/pkgs/main/win-64/matplotlib-3.7.2-py311haa95532_0.conda
https://repo.anaconda.com/pkgs/main/win-64/matplotlib-base-3.7.2-py311hf62ec03_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_fft-1.3.8-py311h2bbff1b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/mkl_random-1.2.4-py311h59b6b97_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numpy-1.26.0-py311hdab7c0b_0.conda
https://repo.anaconda.com/pkgs/main/win-64/numexpr-2.8.4-py311h1fcbade_1.conda
https://repo.anaconda.com/pkgs/main/win-64/scipy-1.11.1-py311hc1ccb85_0.conda
https://repo.anaconda.com/pkgs/main/win-64/pandas-2.0.3-py311hf62ec03_0.conda
https://repo.anaconda.com/pkgs/main/win-64/scikit-learn-1.2.2-py311hd77b12b_1.conda
https://repo.anaconda.com/pkgs/main/win-64/xarray-2023.6.0-py311haa95532_0.conda
